### PR TITLE
Re-fixing #293 for both C* ingress and Stargate C* ingress. 

### LINKED ISSUE #293: Non-Stargate Cassandra ingress is broken.
## Bug Report

**Describe the bug**
I cannot connect with cqlsh using ingress on port 9042.

**To Reproduce**
1. Start a default cluster on Kind with ingress enabled. For simplicity, we'll also disable auth. We'll use distinct and easily identifiable values for releaseName, clusterName, and namespace for reasons that will be apparent in a minute. `custom-values.yaml`:

        k8ssandra:
          namespace: namespace
        cassandra:
          clusterName: clustername
          auth:
            enabled: true
        ingress:
          traefik:
            enabled: true

    Install with:

        helm install releasename ../charts/k8ssandra -n namespace --create-namespace -f custom-values.yaml

2. Attempt to connect using cqlsh:

        $ cqlsh
        Connection error: ('Unable to connect to any servers', {'127.0.0.1:9042': error(61, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})

**Expected behavior**
I expected cqlsh to connect.

**Debugging steps taken**:

1. Verify that docker is listening on port 9042. (PID 664 is Docker)

        $ lsof -PNp 664 | grep LISTEN
        com.docke 664 jakerobb   48u     IPv6 0x6d42f0e5b5da4599      0t0                 TCP *:8082 (LISTEN)
        com.docke 664 jakerobb   66u     IPv6 0x6d42f0e5b5da3279      0t0                 TCP *:8080 (LISTEN)
        com.docke 664 jakerobb   74u     IPv6 0x6d42f0e5b6fd18d9      0t0                 TCP *:9000 (LISTEN)
        com.docke 664 jakerobb   75u     IPv6 0x6d42f0e5b6fd1279      0t0                 TCP *:8443 (LISTEN)
        com.docke 664 jakerobb   76u     IPv4 0x6d42f0e5b7466479      0t0                 TCP localhost:63931 (LISTEN)
        com.docke 664 jakerobb   77u     IPv6 0x6d42f0e5b6fd1f39      0t0                 TCP *:8081 (LISTEN)

    **Docker is in fact _not_ listening on 9042.**
    
    Diagnosis: the `cassandra` ports are not configured in `kind.config.yaml` as provided in our docs.
    Solution: add these lines to the end of the file:

    ```
      - containerPort: 32091
        hostPort: 9042
        protocol: TCP
    ```
    
2. Delete kind cluster and rebuild again with updated kind config; try cqlsh again:

        $ cqlsh
        Connection error: ('Unable to connect to any servers', {'127.0.0.1:9042': OperationTimedOut('errors=Timed out creating connection (5 seconds), last_host=None',)})

    **Docker is listening now, but there's still a problem.**

3. Check the [Traefik dashboard](http://127.0.0.1:9000/dashboard/#/tcp/routers):
    
    image
    
    We can see here that it's not able to find the service. The name of the service it's looking for is obscured by an abstraction layer in the Traefik dashboard, so we need to dig just a bit more:

    * `kubectl -n namespace get services` reports that the Cassandra service is named `clustername-dc1-service`
    * In `traefik.ingressroutes.yaml`, we have configured Traefik to look for `{{ $releaseName }}-{{ $datacenterName }}-service` 

    Changing the ingress spec from:

          routes:
            - match: HostSNI(`*`)
              services:
                - name: {{ $releaseName }}-{{ $datacenterName }}-service

    to 

          routes:
            - match: HostSNI(`*`)
              services:
                - name: {{ $clusterName }}-{{ $datacenterName }}-service

    solves the problem. 

        $ cqlsh                           
        Connected to cluster1 at 127.0.0.1:9042.
        [cqlsh 6.8.0 | Cassandra 3.11.9 | CQL spec 3.4.4 | Native protocol v4]
        Use HELP for help.
        cqlsh> 

PR inbound.

### PR DESCRIPTION
**Pull request by jakerobb**
**What this PR does**:
My previous fix (#294) was trampled in #333. Adding unit tests for it this time, fixing a bug in a test utility function, and doing a bit of minor test cleanup.

**Which issue(s) this PR fixes**:
Fixes #293

**Checklist**
- [x] Changes manually tested
- [x] Chart versions updated (if necessary)
- [x] Automated Tests added/updated
- [x] Documentation added/updated
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: tests/unit/template_stargate_test.go [hunk 1]
```diff
@@ -105,7 +105,7 @@ var _ = Describe("Verify Stargate template", func() {
 		})
 
 		It("changing cluster name", func() {
-			clusterName := Sprintf("k8ssandra-clustername-%s", UniqueIdSuffix)
+			clusterName := Sprintf("k8ssandracluster%s", UniqueIdSuffix)
```
Comment (jakerobb) [inline tests/unit/template_stargate_test.go:108]: As it turns out, the hyphens make it harder to diagnose failures related to name mismatches.

File: tests/unit/utils/traefik/tcpRoutes.go [hunk 2]
```diff
@@ -12,7 +12,7 @@ func VerifyTraefikTCPIngressRoute(ingress traefik.IngressRouteTCP, entrypoint st
 	route := findTraefikTCPRouteByMatch(&ingress.Spec, match)
 	ExpectWithOffset(1, route).ToNot(BeNil(), fmt.Sprintf("No Route found with match=%s for entrypoint=%s", match, entrypoint))
 	service := findTraefikTCPServiceByName(route, backendService)
-	ExpectWithOffset(1, route).ToNot(BeNil(), fmt.Sprintf("No BackendService found with name=%s for match=%s and entrypoint=%s", backendService, match, entrypoint))
+	ExpectWithOffset(1, service).ToNot(BeNil(), fmt.Sprintf("No BackendService found with name=%s for match=%s and entrypoint=%s", backendService, match, entrypoint))
```
Comment (jakerobb) [inline tests/unit/utils/traefik/tcpRoutes.go:15]: Oops! Caught myself in a copypasta. :)

**Review by jeffbanks — APPROVED** [review]
LGTM.

**Review by jsanda — APPROVED** [review]
