### PR TITLE
Fix Cassandra config clobbering when enabling Medusa

### LINKED ISSUE #475: nodetool commands produce noisy output but work fine otherwise
## Bug Report

**Describe the bug**
Running any nodetool command inside the cassandra container produces additional logs (compared to a "traditional" cassandra deployment)

```bash
kubectl exec -ti cassandra-eu-central-1-eu-central-1a-sts-0 -c cassandra -- nodetool  -u $(kubectl get secret cassandra-superuser -o jsonpath="{.data.username}" | base64 --decode ; echo) -pw  $(kubectl get secret cassandra-superuser -o jsonpath="{.data.password}" | base64 --decode ; echo) status
```
```
12:12:25,798 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-tools.xml]
12:12:25,799 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
12:12:25,799 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
12:12:25,800 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/etc/cassandra/logback.xml]
12:12:26,100 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
12:12:26,107 |-INFO in ReconfigureOnChangeFilter{invocationCounter=0} - Will scan for changes in [[/etc/cassandra/logback.xml]] every 60 seconds.
12:12:26,107 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Adding ReconfigureOnChangeFilter as a turbo filter
12:12:26,114 |-INFO in ch.qos.logback.classic.joran.action.JMXConfiguratorAction - begin
12:12:26,607 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
12:12:26,678 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [SYSTEMLOG]
12:12:26,802 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@4f9a3314 - Will use zip compression
12:12:26,905 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
12:12:27,074 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[SYSTEMLOG] - Active log file name: cassandra.logdir_IS_UNDEFINED/system.log
12:12:27,074 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[SYSTEMLOG] - File property is set to [cassandra.logdir_IS_UNDEFINED/system.log]
12:12:27,075 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[SYSTEMLOG] - Failed to create parent directories for [/cassandra.logdir_IS_UNDEFINED/system.log]
12:12:27,076 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[SYSTEMLOG] - openFile(cassandra.logdir_IS_UNDEFINED/system.log,true) call failed. java.io.FileNotFoundException: cassandra.logdir_IS_UNDEFINED/system.log (No such file or directory)
        at java.io.FileNotFoundException: cassandra.logdir_IS_UNDEFINED/system.log (No such file or directory)
        at      at java.io.FileOutputStream.open0(Native Method)
        at      at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at      at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at      at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:28)
        at      at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:148)
        at      at ch.qos.logback.core.FileAppender.start(FileAppender.java:108)
        at      at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:86)
        at      at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
        at      at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
        at      at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
        at      at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
        at      at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
        at      at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:77)
        at      at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:152)
        at      at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
        at      at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at      at org.slf4j.LoggerFactory.bind(LoggerFactory.java:129)
        at      at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
        at      at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
        at      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
        at      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:288)
        at      at org.apache.cassandra.utils.FBUtilities.<clinit>(FBUtilities.java:72)
        at      at org.apache.cassandra.tools.NodeTool.printHistory(NodeTool.java:216)
        at      at org.apache.cassandra.tools.NodeTool.execute(NodeTool.java:184)
        at      at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:56)
12:12:27,076 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
12:12:27,076 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [DEBUGLOG]
12:12:27,078 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@176d53b2 - Will use zip compression
12:12:27,080 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
12:12:27,081 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[DEBUGLOG] - Active log file name: cassandra.logdir_IS_UNDEFINED/debug.log
12:12:27,081 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[DEBUGLOG] - File property is set to [cassandra.logdir_IS_UNDEFINED/debug.log]
12:12:27,081 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[DEBUGLOG] - Failed to create parent directories for [/cassandra.logdir_IS_UNDEFINED/debug.log]
12:12:27,081 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[DEBUGLOG] - openFile(cassandra.logdir_IS_UNDEFINED/debug.log,true) call failed. java.io.FileNotFoundException: cassandra.logdir_IS_UNDEFINED/debug.log (No such file or directory)
        at java.io.FileNotFoundException: cassandra.logdir_IS_UNDEFINED/debug.log (No such file or directory)
        at      at java.io.FileOutputStream.open0(Native Method)
        at      at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at      at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at      at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:28)
        at      at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:148)
        at      at ch.qos.logback.core.FileAppender.start(FileAppender.java:108)
        at      at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:86)
        at      at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
        at      at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
        at      at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
        at      at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
        at      at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
        at      at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:77)
        at      at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:152)
        at      at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
        at      at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at      at org.slf4j.LoggerFactory.bind(LoggerFactory.java:129)
        at      at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
        at      at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
        at      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
        at      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:288)
        at      at org.apache.cassandra.utils.FBUtilities.<clinit>(FBUtilities.java:72)
        at      at org.apache.cassandra.tools.NodeTool.printHistory(NodeTool.java:216)
        at      at org.apache.cassandra.tools.NodeTool.execute(NodeTool.java:184)
        at      at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:56)
12:12:27,081 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
12:12:27,084 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNCDEBUGLOG]
12:12:27,090 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [DEBUGLOG] to ch.qos.logback.classic.AsyncAppender[ASYNCDEBUGLOG]
12:12:27,090 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNCDEBUGLOG] - Attaching appender named [DEBUGLOG] to AsyncAppender.
12:12:27,091 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNCDEBUGLOG] - Setting discardingThreshold to 0
12:12:27,092 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
12:12:27,094 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
12:12:27,097 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
12:12:27,098 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
12:12:27,098 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [SYSTEMLOG] to Logger[ROOT]
12:12:27,098 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
12:12:27,098 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNCDEBUGLOG] to Logger[ROOT]
12:12:27,099 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.cassandra] to DEBUG
12:12:27,099 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.thinkaurelius.thrift] to ERROR
12:12:27,099 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
12:12:27,100 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@971d0d8 - Registering current configuration as safe fallback point

Datacenter: eu-central-1
========================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.244.195.25  70.69 KiB  256          100.0%            6ee92115-880c-4c5f-80f8-e724232fc35e  eu-central-1a

```

**To Reproduce**
1. Deploy k8ssandra
2. Run any nodetool command

**Expected behavior**
Just the "plain" nodetool output

**Screenshots**
n/a

**Environment (please complete the following information):**

* Helm charts version info

Installed via ArgoCD (i.e. through `helm template | kubectl apply -f -`). Therefore no `helm ls` directly possible.
Chart version 1.0.0

* Helm charts user-supplied values

See above. Values.yaml should (not tested though)) be irrelevant, for completeness sake here is what I used though
```
        cassandra:
          # -- The Cassandra version to use. The supported versions include the following:
          #    - 3.11.7
          #    - 3.11.8
          #    - 3.11.9
          #    - 3.11.10
          #    - 4.0.0
          version: "3.11.10"

          # -- Specifies the image to use for a particular Cassandra version. Exercise
          # care and caution with changing these values! cass-operator is not designed to work with
          # arbitrary Cassandra images. It expects the cassandra container to be running
          # management-api images. If you do want to change one of these mappings, the new value
          # should be a management-api image.
          versionImageMap:
            3.11.7: datastax/cassandra-mgmtapi-3_11_7:v0.1.22
            3.11.8: datastax/cassandra-mgmtapi-3_11_8:v0.1.22
            3.11.9: datastax/cassandra-mgmtapi-3_11_9:v0.1.22
            3.11.10: datastax/cassandra-mgmtapi-3_11_10:v0.1.22
            4.0.0: datastax/cassandra-mgmtapi-4_0_0:v0.1.22

          # -- Overrides the default image mappings. This is intended for advanced use cases
          # like development or testing. By default the Cassandra version has to be one that is in
          # versionImageMap. Template rendering will fail if the version is not in the map. When
          # you set the image directly, the version mapping check is skipped. Note that you are
          # still constrained to the versions supported by cass-operator.
          #
          # image:

          # -- Cluster name defaults to release name when not specified.
          clusterName: "cassandra"

          # -- Authentication and authorization related settings.
          auth:
            enabled: true

            # -- Configures the default Cassandra superuser when authentication is
            # enabled. If neither `superuser.secret` nor `superuser.username` are set,
            # then a user and a secret with the user's credentials will be created. The
            # username and secret name will be of the form {clusterName}-superuser. The
            # password will be a random 20 character password. If `superuser.secret` is
            # set, then the Cassandra user will be created from the contents of the
            # secret. If `superuser.secret` is not set and if `superuser.username` is
            # set, a secret will be generated using the specified username. The
            # password will be generated as previously described.
            #
            # JMX credentials will also be created for the superuser. The same
            # username/password that is used here will be used for JMX. If you change
            # the Cassandra superuser credentials through cqlsh for example, the JMX
            # credentials will not be updated. You need to update the credentials via
            # helm upgrade in order for the change to propagate to JMX. This will be
            # fixed in https://github.com/k8ssandra/k8ssandra/issues/323.
            superuser:
              secret: ""
              username: ""
          cassandraLibDirVolume:
            storageClass: local-path
            size: 5Gi
          heap:
            size: 1G
            newGenSize: 1G

          # -- Permits running multiple Cassandra pods per Kubernetes worker. If enabled
          # resources.limits and resources.requests **must** be defined.
          allowMultipleNodesPerWorker: true

          resources:
            limits:
              cpu: '1'
              memory: 4Gi
            requests:
              cpu: '1'
              memory: 2Gi


          datacenters:
          - name: eu-central-1
            size: 1
            racks:
            - name: eu-central-1a

        stargate:
          enabled: false

        reaper:
          # -- When enabled, Reaper automatically sets up repair schedules for all
          # non-system keypsaces. Repear monitors the cluster so that as keyspaces are
          # added or removed repair schedules will be added or removed respectively.
          autoschedule: true

          # -- Enable Reaper resources as part of this release. Note that Reaper uses
          # Cassandra's JMX APIs to perform repairs. When Reaper is enabled, Cassandra
          # will also be configured to allow remote JMX access. JMX authentication
          # will be configured in Cassandra with credentials only created for Reaper
          # in order to limit access.
          enabled: true

          # -- Configures the Cassandra user used by Reaper when authentication is
          # enabled. If neither cassandraUser.secret nor casandraUser.username are
          # set, then a Cassandra user and a secret with the user's credentials will
          # be created. The username will be reaper. The secret name will be of the
          # form {clusterName}-reaper. The password will be a random 20 character
          # password. If cassandraUser.secret is set, then the Cassandra user will be
          # created from the contents of the secret. If cassandraUser.secret is not
          # set and if cassandraUser.username is set, a secret will be generated using
          # the specified username. The password will be generated as previously
          # described.
          cassandraUser:
            secret: ""
            username: ""

          # -- Configures JMX access to the Cassandra cluster. Reaper requires remote
          # JMX access to perform repairs. The Cassandra cluster will be configured
          # with remote JMX access enabled when Reaper is deployed. The JMX access
          # will be configured to use authentication.
          #
          # If neither `jmx.secret` nor `jmx.username` are set, then a default user and
          # secret with the user's credentials will be created.
          jmx:
            secret: ""
            # -- Username that Reaper will use for JMX access. If left blank a random,
            # alphanumeric string will be generated.
            username: ""

        medusa:
          # -- Enable Medusa resources as part of this release. If enabled,
          # `bucketName` and `bucketSecret` **must** be defined.
          enabled: true

          # Configures the Medusa image which is built from
          # https://github.com/thelastpickle/cassandra-medusa/tree/master/k8s.
          image:
            # -- Specifies the container repository for Medusa
            repository: docker.io/k8ssandra/medusa
            # -- Tag of an image within the specified repository
            tag: 0.9.0
            # -- The image pull policy
            pullPolicy: IfNotPresent

          # -- Configures the Cassandra user used by Medusa when authentication is
          # enabled. If neither `cassandraUser.secret` nor `casandraUser.username` are
          # set, then a Cassandra user and a secret will be created. The username will
          # be medusa. The secret name will be of the form {clusterName}-medusa. The
          # password will be a random 20 character password. If `cassandraUser.secret`
          # is set, then the Cassandra user will be created from the contents of the
          # secret. If `cassandraUser.secret` is not set and if
          # `cassandraUser.username` is set, a secret will be generated using the
          # specified username. The password will be generated as previously
          # described.
          cassandraUser:
            secret: ""
            username: ""

          # -- Enables usage of a bucket across multiple clusters.
          multiTenant: false

          # -- API interface used by the object store. Supported values include `s3`, 's3_compatible'
          # and `gcs`. For pod mapped storage, use 'local'
          storage: local

          # -- Optional properties for storage. Supported values depend on the type of the storage.
          storage_properties:
            bucket_name: backups
            # Define region for s3 / s3_compatible
            # region: eu-west-1

            # For s3_compatible option, one must define target host
            # host: 192.168.1.201

            # For s3_compatible option, port is optional
            # port: 9000

          # Is SSL used or not for s3_compatible connection
          # secure: false

          # -- Name of the remote storage bucket where backups will be stored. If using 'local' storage, set the
          # path of the local storage here.
          bucketName: /tmp

          # -- Name of the Kubernetes `Secret` that stores the key file for the
          # storage provider's API
          storageSecret: medusa-bucket-key

        monitoring:
          grafana:
            provision_dashboards: false

          prometheus:
            provision_service_monitors: false

        cass-operator:
          enabled: true

        reaper-operator:
          enabled: true

        kube-prometheus-stack:
          enabled: false

          alertmanager:
            enabled: false
            serviceMonitor:
              selfMonitor: false

          prometheusOperator:
            enabled: false

          prometheus:
            # -- Provisions an instance of Prometheus as part of this release
            enabled: false

            # -- Allows for tweaking of the Prometheus installation's configuration.
            # Common parameters include `externalUrl: http://localhost:9090/prometheus`
            # and `routePrefix: /prometheus` for running Prometheus resources under a
            # specific path (`/prometheus` in this example).
            prometheusSpec:
              # -- Prefixes all Prometheus routes with the specified value. It is useful
              # for ingresses which do not rewrite URLs.
              routePrefix: /

              # -- An external URL at which Prometheus will be reachable.
              externalUrl: ""

            ingress:
              # -- Enable templating of ingress resources for external prometheus
              # traffic
              enabled: false
              # -- Path-based routing rules, `/prometheus` is possible if the
              # appropriate changes are made to `prometheusSpec`
              paths: []

            serviceMonitor:
              # Disable monitoring the Prometheus instance
              selfMonitor: false

          grafana:
            enabled: false
            ingress:
              enabled: false
            serviceMonitor:
              selfMonitor: false
            defaultDashboardsEnabled: false
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-rc.0", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.16", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

minikube with kvm2

**Additional context**

Note that this was discussed in https://github.com/k8ssandra/k8ssandra/pull/336 with a link to upstream https://issues.apache.org/jira/browse/CASSANDRA-16199
I.e. this issue is mainly there for people like me who are surprised by the additional (but benign) output.

### PR DESCRIPTION
**Pull request by emerkle826**
**What this PR does**:
This PR adds an init container that sets up the initial Cassandra config in `/etc/cassandra` from the base Cassandra image. Previously, when enabling Medusa, `/etc/cassandra` would be shadow mounted with an empty directory and only config-builder contents would be copied to `/etc/cassandra`, resulting in a fair amount of missing config.

**Which issue(s) this PR fixes**:
Fixes #475 

**Checklist**
- [x] Changes manually tested
- [x] Chart versions updated (if necessary)
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by emerkle826** [comment]
@jsanda A nice bonus of adding the Management API image as a base Cassandra config init container is we no longer need the Cassandra 4 check to add things like `jvm8-client.options`. So this whole section goes away:
https://github.com/k8ssandra/k8ssandra/blob/main/charts/k8ssandra/templates/cassandra/cassdc.yaml#L157-L189

File: tests/unit/template_cassdc_test.go [hunk 1]
```diff
@@ -725,7 +730,8 @@ var _ = Describe("Verify CassandraDatacenter template", func() {
 			verifyMedusaVolumeMounts(medusaContainer)
 
 			Expect(len(cassdc.Spec.PodTemplateSpec.Spec.Volumes)).To(Equal(3))
-			Expect(cassdc.Spec.PodTemplateSpec.Spec.Volumes[0].Name).To(Equal(medusaConfigVolumeName))
+			Expect(cassdc.Spec.PodTemplateSpec.Spec.Volumes[0].Name).To(Equal(CassandraConfigVolumeName))
```
Comment (jsanda) [inline tests/unit/template_cassdc_test.go:733]: We should update the volume checks so that they do not rely on order, similar to what we do with containers. It will make the tests less brittle. 

Note that we do care about order for initContainers though.

**Review by jsanda — CHANGES_REQUESTED** [review]

File: charts/k8ssandra/templates/cassandra/cassdc.yaml [hunk 2]
```diff
@@ -207,7 +185,7 @@ spec:
         volumeMounts:
           - name: {{ include "medusa.configMapName" . }}
             mountPath: /etc/medusa
-          - name: server-config
+          - name: cassandra-config
```
[the remark this answers is not in the document]
Comment (emerkle826) [reply charts/k8ssandra/templates/cassandra/cassdc.yaml:188]: I think you are right. The `cassandra-config` volume mount will eventually have all the bits we need, but it's not until the `cassandra` container kicks in that it copies the updated configs from `/config` over to `/etc/cassandra`.

I need to test this some more to make sure I get this bit right. The idea here is to have all of the config dumped into the `cassandra-config` volume mount, as my intention is to only ever use that volume mount for `/etc/cassandra`, with the exception of the first init container, since I don't want to clobber what's in the management api image until after I've copied them out.

**Comment by jsanda** [comment]
@emerkle826 are you ready for another review?

**Comment by emerkle826** [comment]
> @emerkle826 are you ready for another review?

@jsanda Yes please.

File: charts/k8ssandra/templates/cassandra/cassdc.yaml [hunk 3]
```diff
@@ -114,6 +114,17 @@ spec:
   podTemplateSpec:
     spec:
       initContainers:
+      - name: base-config-init
+        image: {{ default (get .Values.cassandra.versionImageMap .Values.cassandra.version) .Values.cassandra.image }}
```
Comment (jsanda) [inline charts/k8ssandra/templates/cassandra/cassdc.yaml:118]: We use this template in a couple places now to get the Cassandra image. It is a bit of a mouthful. Can you create a helper template for this in _helpers.tpl? Take a look at https://github.com/k8ssandra/k8ssandra/blob/main/charts/k8ssandra/templates/_helpers.tpl#L12 for an example.

**Review by jsanda — CHANGES_REQUESTED** [review]

File: charts/k8ssandra/templates/cassandra/cassdc.yaml (hunk 3 above)
Comment (emerkle826) [reply charts/k8ssandra/templates/cassandra/cassdc.yaml:118]: will do

**Review by jsanda — APPROVED** [review]
Thanks @emerkle826!
